///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProtocolMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 8
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  ProtocolMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  ProtocolMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class ProtocolMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 8
  }
}
*/

  ProtocolMetaPagination? pagination;

  ProtocolMeta({
    this.pagination,
  });
  ProtocolMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? ProtocolMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class ProtocolDataAttributesProtocolTypeDataAttributes {
/*
{
  "createdAt": "2022-05-21T17:17:20.074Z",
  "updatedAt": "2022-05-24T15:56:58.945Z",
  "publishedAt": "2022-05-21T17:17:23.228Z",
  "pType": "محلى"
}
*/

  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  String? pType;

  ProtocolDataAttributesProtocolTypeDataAttributes({
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.pType,
  });
  ProtocolDataAttributesProtocolTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    pType = json['pType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    data['pType'] = pType;
    return data;
  }
}

class ProtocolDataAttributesProtocolTypeData {
/*
{
  "id": 1,
  "attributes": {
    "createdAt": "2022-05-21T17:17:20.074Z",
    "updatedAt": "2022-05-24T15:56:58.945Z",
    "publishedAt": "2022-05-21T17:17:23.228Z",
    "pType": "محلى"
  }
}
*/

  int? id;
  ProtocolDataAttributesProtocolTypeDataAttributes? attributes;

  ProtocolDataAttributesProtocolTypeData({
    this.id,
    this.attributes,
  });
  ProtocolDataAttributesProtocolTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? ProtocolDataAttributesProtocolTypeDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProtocolDataAttributesProtocolType {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "createdAt": "2022-05-21T17:17:20.074Z",
      "updatedAt": "2022-05-24T15:56:58.945Z",
      "publishedAt": "2022-05-21T17:17:23.228Z",
      "pType": "محلى"
    }
  }
}
*/

  ProtocolDataAttributesProtocolTypeData? data;

  ProtocolDataAttributesProtocolType({
    this.data,
  });
  ProtocolDataAttributesProtocolType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ProtocolDataAttributesProtocolTypeData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class ProtocolDataAttributesCountry {
/*
{
  "data": null
}
*/

  String? data;

  ProtocolDataAttributesCountry({
    this.data,
  });
  ProtocolDataAttributesCountry.fromJson(Map<String, dynamic> json) {
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['data'] = this.data;
    return data;
  }
}

class ProtocolDataAttributes {
/*
{
  "Name": "تجديد برتوكول مع جامعة الفيوم",
  "createdAt": "2022-05-21T17:17:07.139Z",
  "updatedAt": "2022-05-24T15:57:24.013Z",
  "publishedAt": "2022-05-21T17:17:08.233Z",
  "country": {
    "data": null
  },
  "protocol_type": {
    "data": {
      "id": 1,
      "attributes": {
        "createdAt": "2022-05-21T17:17:20.074Z",
        "updatedAt": "2022-05-24T15:56:58.945Z",
        "publishedAt": "2022-05-21T17:17:23.228Z",
        "pType": "محلى"
      }
    }
  }
}
*/

  String? Name;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  ProtocolDataAttributesCountry? country;
  ProtocolDataAttributesProtocolType? protocolType;

  ProtocolDataAttributes({
    this.Name,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.country,
    this.protocolType,
  });
  ProtocolDataAttributes.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    country = (json['country'] != null) ? ProtocolDataAttributesCountry.fromJson(json['country']) : null;
    protocolType = (json['protocol_type'] != null) ? ProtocolDataAttributesProtocolType.fromJson(json['protocol_type']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (country != null) {
      data['country'] = country!.toJson();
    }
    if (protocolType != null) {
      data['protocol_type'] = protocolType!.toJson();
    }
    return data;
  }
}

class ProtocolData {
/*
{
  "id": 1,
  "attributes": {
    "Name": "تجديد برتوكول مع جامعة الفيوم",
    "createdAt": "2022-05-21T17:17:07.139Z",
    "updatedAt": "2022-05-24T15:57:24.013Z",
    "publishedAt": "2022-05-21T17:17:08.233Z",
    "country": {
      "data": null
    },
    "protocol_type": {
      "data": {
        "id": 1,
        "attributes": {
          "createdAt": "2022-05-21T17:17:20.074Z",
          "updatedAt": "2022-05-24T15:56:58.945Z",
          "publishedAt": "2022-05-21T17:17:23.228Z",
          "pType": "محلى"
        }
      }
    }
  }
}
*/

  int? id;
  ProtocolDataAttributes? attributes;

  ProtocolData({
    this.id,
    this.attributes,
  });
  ProtocolData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? ProtocolDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class Protocol {
/*
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "Name": "تجديد برتوكول مع جامعة الفيوم",
        "createdAt": "2022-05-21T17:17:07.139Z",
        "updatedAt": "2022-05-24T15:57:24.013Z",
        "publishedAt": "2022-05-21T17:17:08.233Z",
        "country": {
          "data": null
        },
        "protocol_type": {
          "data": {
            "id": 1,
            "attributes": {
              "createdAt": "2022-05-21T17:17:20.074Z",
              "updatedAt": "2022-05-24T15:56:58.945Z",
              "publishedAt": "2022-05-21T17:17:23.228Z",
              "pType": "محلى"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 8
    }
  }
}
*/

  List<ProtocolData?>? data;
  ProtocolMeta? meta;

  Protocol({
    this.data,
    this.meta,
  });
  Protocol.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProtocolData>[];
      v.forEach((v) {
        arr0.add(ProtocolData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? ProtocolMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
