///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProtocolTypeMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 2
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  ProtocolTypeMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  ProtocolTypeMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class ProtocolTypeMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 2
  }
}
*/

  ProtocolTypeMetaPagination? pagination;

  ProtocolTypeMeta({
    this.pagination,
  });
  ProtocolTypeMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? ProtocolTypeMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class ProtocolTypeDataAttributes {
/*
{
  "createdAt": "2022-05-21T17:17:20.074Z",
  "updatedAt": "2022-05-24T15:56:58.945Z",
  "publishedAt": "2022-05-21T17:17:23.228Z",
  "pType": "محلى"
}
*/

  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  String? pType;

  ProtocolTypeDataAttributes({
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.pType,
  });
  ProtocolTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    pType = json['pType']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    data['pType'] = pType;
    return data;
  }
}

class ProtocolTypeData {
/*
{
  "id": 1,
  "attributes": {
    "createdAt": "2022-05-21T17:17:20.074Z",
    "updatedAt": "2022-05-24T15:56:58.945Z",
    "publishedAt": "2022-05-21T17:17:23.228Z",
    "pType": "محلى"
  }
}
*/

  int? id;
  ProtocolTypeDataAttributes? attributes;

  ProtocolTypeData({
    this.id,
    this.attributes,
  });
  ProtocolTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? ProtocolTypeDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class ProtocolType {
/*
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "createdAt": "2022-05-21T17:17:20.074Z",
        "updatedAt": "2022-05-24T15:56:58.945Z",
        "publishedAt": "2022-05-21T17:17:23.228Z",
        "pType": "محلى"
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 2
    }
  }
}
*/

  List<ProtocolTypeData?>? data;
  ProtocolTypeMeta? meta;

  ProtocolType({
    this.data,
    this.meta,
  });
  ProtocolType.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProtocolTypeData>[];
      v.forEach((v) {
        arr0.add(ProtocolTypeData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? ProtocolTypeMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
