///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentTransactionMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 86
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  StudentTransactionMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  StudentTransactionMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class StudentTransactionMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 86
  }
}
*/

  StudentTransactionMetaPagination? pagination;

  StudentTransactionMeta({
    this.pagination,
  });
  StudentTransactionMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? StudentTransactionMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class StudentTransactionDataAttributesSurveyItemDataAttributes {
/*
{
  "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
  "createdAt": "2022-05-24T07:07:45.796Z",
  "updatedAt": "2022-05-24T07:07:47.048Z",
  "publishedAt": "2022-05-24T07:07:47.045Z"
}
*/

  String? Description;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  StudentTransactionDataAttributesSurveyItemDataAttributes({
    this.Description,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  StudentTransactionDataAttributesSurveyItemDataAttributes.fromJson(Map<String, dynamic> json) {
    Description = json['Description']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Description'] = Description;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class StudentTransactionDataAttributesSurveyItemData {
/*
{
  "id": 7,
  "attributes": {
    "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
    "createdAt": "2022-05-24T07:07:45.796Z",
    "updatedAt": "2022-05-24T07:07:47.048Z",
    "publishedAt": "2022-05-24T07:07:47.045Z"
  }
}
*/

  int? id;
  StudentTransactionDataAttributesSurveyItemDataAttributes? attributes;

  StudentTransactionDataAttributesSurveyItemData({
    this.id,
    this.attributes,
  });
  StudentTransactionDataAttributesSurveyItemData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentTransactionDataAttributesSurveyItemDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentTransactionDataAttributesSurveyItem {
/*
{
  "data": {
    "id": 7,
    "attributes": {
      "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
      "createdAt": "2022-05-24T07:07:45.796Z",
      "updatedAt": "2022-05-24T07:07:47.048Z",
      "publishedAt": "2022-05-24T07:07:47.045Z"
    }
  }
}
*/

  StudentTransactionDataAttributesSurveyItemData? data;

  StudentTransactionDataAttributesSurveyItem({
    this.data,
  });
  StudentTransactionDataAttributesSurveyItem.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? StudentTransactionDataAttributesSurveyItemData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class StudentTransactionDataAttributesAcademicYearDataAttributes {
/*
{
  "Year": "2019/2020",
  "createdAt": "2022-05-21T14:58:59.207Z",
  "updatedAt": "2022-05-23T21:20:45.372Z",
  "publishedAt": "2022-05-21T14:59:00.714Z"
}
*/

  String? Year;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  StudentTransactionDataAttributesAcademicYearDataAttributes({
    this.Year,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  StudentTransactionDataAttributesAcademicYearDataAttributes.fromJson(Map<String, dynamic> json) {
    Year = json['Year']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Year'] = Year;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class StudentTransactionDataAttributesAcademicYearData {
/*
{
  "id": 2,
  "attributes": {
    "Year": "2019/2020",
    "createdAt": "2022-05-21T14:58:59.207Z",
    "updatedAt": "2022-05-23T21:20:45.372Z",
    "publishedAt": "2022-05-21T14:59:00.714Z"
  }
}
*/

  int? id;
  StudentTransactionDataAttributesAcademicYearDataAttributes? attributes;

  StudentTransactionDataAttributesAcademicYearData({
    this.id,
    this.attributes,
  });
  StudentTransactionDataAttributesAcademicYearData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentTransactionDataAttributesAcademicYearDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentTransactionDataAttributesAcademicYear {
/*
{
  "data": {
    "id": 2,
    "attributes": {
      "Year": "2019/2020",
      "createdAt": "2022-05-21T14:58:59.207Z",
      "updatedAt": "2022-05-23T21:20:45.372Z",
      "publishedAt": "2022-05-21T14:59:00.714Z"
    }
  }
}
*/

  StudentTransactionDataAttributesAcademicYearData? data;

  StudentTransactionDataAttributesAcademicYear({
    this.data,
  });
  StudentTransactionDataAttributesAcademicYear.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? StudentTransactionDataAttributesAcademicYearData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class StudentTransactionDataAttributes {
/*
{
  "Percentage": 75,
  "createdAt": "2022-05-24T09:21:05.619Z",
  "updatedAt": "2022-05-24T09:21:06.635Z",
  "publishedAt": "2022-05-24T09:21:06.632Z",
  "academic_year": {
    "data": {
      "id": 2,
      "attributes": {
        "Year": "2019/2020",
        "createdAt": "2022-05-21T14:58:59.207Z",
        "updatedAt": "2022-05-23T21:20:45.372Z",
        "publishedAt": "2022-05-21T14:59:00.714Z"
      }
    }
  },
  "survey_item": {
    "data": {
      "id": 7,
      "attributes": {
        "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
        "createdAt": "2022-05-24T07:07:45.796Z",
        "updatedAt": "2022-05-24T07:07:47.048Z",
        "publishedAt": "2022-05-24T07:07:47.045Z"
      }
    }
  }
}
*/

  int? Percentage;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  StudentTransactionDataAttributesAcademicYear? academicYear;
  StudentTransactionDataAttributesSurveyItem? surveyItem;

  StudentTransactionDataAttributes({
    this.Percentage,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.academicYear,
    this.surveyItem,
  });
  StudentTransactionDataAttributes.fromJson(Map<String, dynamic> json) {
    Percentage = json['Percentage']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    academicYear = (json['academic_year'] != null) ? StudentTransactionDataAttributesAcademicYear.fromJson(json['academic_year']) : null;
    surveyItem = (json['survey_item'] != null) ? StudentTransactionDataAttributesSurveyItem.fromJson(json['survey_item']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Percentage'] = Percentage;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (academicYear != null) {
      data['academic_year'] = academicYear!.toJson();
    }
    if (surveyItem != null) {
      data['survey_item'] = surveyItem!.toJson();
    }
    return data;
  }
}

class StudentTransactionData {
/*
{
  "id": 50,
  "attributes": {
    "Percentage": 75,
    "createdAt": "2022-05-24T09:21:05.619Z",
    "updatedAt": "2022-05-24T09:21:06.635Z",
    "publishedAt": "2022-05-24T09:21:06.632Z",
    "academic_year": {
      "data": {
        "id": 2,
        "attributes": {
          "Year": "2019/2020",
          "createdAt": "2022-05-21T14:58:59.207Z",
          "updatedAt": "2022-05-23T21:20:45.372Z",
          "publishedAt": "2022-05-21T14:59:00.714Z"
        }
      }
    },
    "survey_item": {
      "data": {
        "id": 7,
        "attributes": {
          "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
          "createdAt": "2022-05-24T07:07:45.796Z",
          "updatedAt": "2022-05-24T07:07:47.048Z",
          "publishedAt": "2022-05-24T07:07:47.045Z"
        }
      }
    }
  }
}
*/

  int? id;
  StudentTransactionDataAttributes? attributes;

  StudentTransactionData({
    this.id,
    this.attributes,
  });
  StudentTransactionData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentTransactionDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentTransaction {
/*
{
  "data": [
    {
      "id": 50,
      "attributes": {
        "Percentage": 75,
        "createdAt": "2022-05-24T09:21:05.619Z",
        "updatedAt": "2022-05-24T09:21:06.635Z",
        "publishedAt": "2022-05-24T09:21:06.632Z",
        "academic_year": {
          "data": {
            "id": 2,
            "attributes": {
              "Year": "2019/2020",
              "createdAt": "2022-05-21T14:58:59.207Z",
              "updatedAt": "2022-05-23T21:20:45.372Z",
              "publishedAt": "2022-05-21T14:59:00.714Z"
            }
          }
        },
        "survey_item": {
          "data": {
            "id": 7,
            "attributes": {
              "Description": "العيادة الطبية والمستشفى الجامعى تقدم خدمة رعاية صحية جيدة للطلاب",
              "createdAt": "2022-05-24T07:07:45.796Z",
              "updatedAt": "2022-05-24T07:07:47.048Z",
              "publishedAt": "2022-05-24T07:07:47.045Z"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 86
    }
  }
}
*/

  List<StudentTransactionData?>? data;
  StudentTransactionMeta? meta;

  StudentTransaction({
    this.data,
    this.meta,
  });
  StudentTransaction.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <StudentTransactionData>[];
      v.forEach((v) {
        arr0.add(StudentTransactionData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? StudentTransactionMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
