///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserdataUser {
/*
{
  "id": 6,
  "username": "alyaa osama",
  "email": "alyaaosama@gmail.com",
  "provider": "local",
  "confirmed": true,
  "blocked": false,
  "createdAt": "2022-06-10T15:17:02.192Z",
  "updatedAt": "2022-06-10T15:17:02.192Z"
}
*/

  int? id;
  String? username;
  String? email;
  String? provider;
  bool? confirmed;
  bool? blocked;
  String? createdAt;
  String? updatedAt;

  UserdataUser({
    this.id,
    this.username,
    this.email,
    this.provider,
    this.confirmed,
    this.blocked,
    this.createdAt,
    this.updatedAt,
  });
  UserdataUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    username = json['username']?.toString();
    email = json['email']?.toString();
    provider = json['provider']?.toString();
    confirmed = json['confirmed'];
    blocked = json['blocked'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['email'] = email;
    data['provider'] = provider;
    data['confirmed'] = confirmed;
    data['blocked'] = blocked;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class Userdata {
/*
{
  "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjU0ODg2MjA2LCJleHAiOjE2NTc0NzgyMDZ9.OZVtm8KifiIJnJYmWWEAtHFyKhhrvxq36BLrtX9pJ4o",
  "user": {
    "id": 6,
    "username": "alyaa osama",
    "email": "alyaaosama@gmail.com",
    "provider": "local",
    "confirmed": true,
    "blocked": false,
    "createdAt": "2022-06-10T15:17:02.192Z",
    "updatedAt": "2022-06-10T15:17:02.192Z"
  }
}
*/

  String? jwt;
  UserdataUser? user;

  Userdata({
    this.jwt,
    this.user,
  });
  Userdata.fromJson(Map<String, dynamic> json) {
    jwt = json['jwt']?.toString();
    user = (json['user'] != null) ? UserdataUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['jwt'] = jwt;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
