///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Users {
/*
{
  "id": 6,
  "username": "alyaa osama",
  "email": "alyaaosama@gmail.com",
  "provider": "local",
  "confirmed": true,
  "blocked": false,
  "createdAt": "2022-06-10T15:17:02.192Z",
  "updatedAt": "2022-06-17T04:16:18.396Z",
  "visible": "creator2"
}
*/

  int? id;
  String? username;
  String? email;
  String? provider;
  bool? confirmed;
  bool? blocked;
  String? createdAt;
  String? updatedAt;
  String? visible;

  Users({
    this.id,
    this.username,
    this.email,
    this.provider,
    this.confirmed,
    this.blocked,
    this.createdAt,
    this.updatedAt,
    this.visible,
  });
  Users.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    username = json['username']?.toString();
    email = json['email']?.toString();
    provider = json['provider']?.toString();
    confirmed = json['confirmed'];
    blocked = json['blocked'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    visible = json['visible']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['email'] = email;
    data['provider'] = provider;
    data['confirmed'] = confirmed;
    data['blocked'] = blocked;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['visible'] = visible;
    return data;
  }
}
class User{
  List<Users>? users;
  User({
    this.users
});



}

